language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: "50.0"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester@v5.0.0
- bower install
script: xvfb-run wct
cache:
  directories:
    - node_modules